## Dasar-dasar Pemrograman Pytorch

Pytorch merupakan salah satu library pembelajaran mesin dan deep learning populer yang dikembangkan oleh Facebook.
Instalasi : www.pytorch.org


In [1]:
#import library pytorch
import torch

In [5]:
# membuat array dengan pytorch
a = torch.tensor([1,2,3])
print(a)

tensor([1, 2, 3])


In [6]:
# membuat array berisi float number dengan pytorch, 
# cukup dengan menulis salah satu datanya dengan tipe float, maka otomatis semuanya akan berubah menjadi tipe data float
b = torch.tensor([1,2.0,3]) #2.0 bertipe float
print(b)

tensor([1., 2., 3.])


In [7]:
# mengubah tensor ke numpy dengan menggunakan .numpy()
b.numpy()

array([1., 2., 3.], dtype=float32)

In [9]:
# mengubah numpy array ke tensor menggunakan torch.from_numpy()
torch.from_numpy(b.numpy())

tensor([1., 2., 3.])

In [13]:
# membuat bilangan e^x
c = torch.tensor([1,2,3,4,5])
print(c)
c_Exp = torch.exp(c)
print(c_Exp)

tensor([1, 2, 3, 4, 5])
tensor([  2.7183,   7.3891,  20.0855,  54.5981, 148.4132])


In [12]:
# membuat partisi dari bilangan antara 0 sampai 10, dengan 5 partisi.
d = torch.linspace(0,10,5)
print(d)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [16]:
# membuat list dengan range 0 sampai 10
e = torch.arange(0,10)
print(e)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [24]:
# reshape pada pytorch dengan menggunakan .view()
e_2d = e.view(2,5) # mengubah menjadi 2 baris 5 kolom
print(e_2d)
f = e.view(-1,2) # mengubah ke 2 kolom dengan jumlah baris terhitung otomatis
print(f)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [23]:
# membuat array 2D
arr_2D = torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])
print(arr_2D)
print("jumlah dimensi = ", arr_2D.dim())

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
jumlah dimensi =  2
